site_name: AaronPB
site_url: https://aaronpb.github.io/
site_author: Aarón Poyatos
site_description: >-
  This is my website with some information about my projects and hobbies.
copyright: >
  Copyright &copy; 2025 AaronPB –
  <a href="#__consent">Change cookie settings</a>
nav:
  - Home: index.md
  - Blog: blog/index.md
  - Research:
    - research/index.md
    - Publications: research/publications.md
    - Patents & Utility Models: research/patents.md
  - Hobbies:
    - hobbies/index.md
    - Videogames: hobbies/videogames.md
    - Volunteering: hobbies/volunteering.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  font:
    text: Ubuntu
  icon:
    logo: fontawesome/solid/id-card-clip
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: red
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: red
## extra_css:
##   - stylesheets/extra.css
## extra_javascript:
##   - javascripts/extra.js
plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - News
        - Tutorials
        - Videogames
      pagination_per_page: 5
  - tags
  - meta
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AaronPB
      name: GitHub profile
    - icon: fontawesome/brands/linkedin
      link: https://es.linkedin.com/in/aaron-raul-poyatos-bakker
      name: LinkedIn profile
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage